apps/authentication/urls.py
from django.urls import path
from .views.login.views import *

urlpatterns = [
    path('login/',LoginFormView.as_view(),name='login'),
]

apps/dashboard/urls.py
from django.urls import path

urlpatterns = []

apps/web/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

soleg/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.web.urls','wb'), namespace='wb')),
    path('dashboard/', include(('apps.dashboard.urls', 'dash'), namespace='dash')),
    path('auth/',include(('apps.authentication.urls','ath'),namespace='ath')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/web/models.py
from django.db import models

# Create your models here.

apps/authentication/views/login/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.http import JsonResponse
from apps.authentication.forms.login.form_login import *
from django.views.generic import RedirectView
from soleg.secretkeys import *

class LoginFormView(LoginView):
    form_class = LoginForm
    template_name = 'login/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            form = self.form_class(data=request.POST)
            if self.login_recaptcha(request):
                if form.is_valid():
                    self.form_valid(form=form)
                    if not form.cleaned_data['remember_me']:
                        request.session.set_expiry(0) 
                        request.session.modified = True
                    data['message'] = 'Bienvenido'
                    return self.response_codes(data,200)
                else:
                    data['message'] = form.errors
                    return self.response_codes(data,400)
            else:
                data['message'] = {
                    'g-recaptcha-response':['El reCAPTCHA no es valido, por favor intente de nuevo o refresque la pagina.']
                }
                return self.response_codes(data,498)
        else:
            return redirect(self.success_url)

    
    def login_recaptcha(self, request):
        recaptcha_response = request.POST.get('g-recaptcha-response')
        url = 'https://www.google.com/recaptcha/api/siteverify'
        values = {
                'secret': RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response,
                }
        datas = urllib.parse.urlencode(values).encode()
        req =  urllib.request.Request(url, data=datas)
        response = urllib.request.urlopen(req)
        result = json.loads(response.read().decode())
        if not result['success']:
            return False
        return True

    def response_codes(self,data,code):
        response = JsonResponse(data)
        response.status_code = code
        return response

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Iniciar Sesión'
        context['creador'] = 'Josue Lopez'
        return context

apps/dashboard/views.py
from django.shortcuts import render

# Create your views here.

apps/web/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['creador'] = 'Josue Lopez'
        return context

apps/authentication/templates/login.html
{% extends 'login/base-login.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %}SOLEG - Iniciar sesión{% endblock title %}
{% block content %}
<body>
    <div class="account-pages my-5 pt-sm-5">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-5">
                    <div class="card overflow-hidden">
                        <div class="bg-secondary bg-soft">
                            <div class="d-flex justify-content-center">

                                <div class="col-5 align-self-end">
                                    <img src="{% static 'img/logo-soleg-negro.png' %}" alt="" class="img-fluid">
                                </div>
                            </div>
                        </div>
                        <div class="card-body pt-2"> 
                            <div class="p-2">
                                <form class="form-horizontal">
                                    <div class="mb-3">
                                        <label for="username" class="form-label">Usuario</label>
                                        <input type="text" class="form-control" id="username" placeholder="ingresa el usuario">
                                    </div>
            
                                    <div class="mb-3">
                                        <label class="form-label">Contraseña</label>
                                        <div class="input-group auth-pass-inputgroup">
                                            <input type="password" class="form-control" placeholder="ingresa la contraseña" aria-label="Password" aria-describedby="password-addon">
                                            <button class="btn btn-light " type="button" id="password-addon"><i class="mdi mdi-eye-outline"></i></button>
                                        </div>
                                    </div>

                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" id="remember-check">
                                        <label class="form-check-label" for="remember-check">
                                            Recuerdame
                                        </label>
                                    </div>
                                    
                                    <div class="mt-3 d-grid">
                                        <button class="btn btn-primary waves-effect waves-light" type="submit">Iniciar sesión</button>
                                    </div>
        
                                    <div class="mt-4 text-center">
                                        <a href="" class="text-muted"><i class="mdi mdi-lock me-1"></i> Olvidaste tu contraseña?</a>
                                    </div>
                                </form>
                            </div>
        
                        </div>
                    </div>
                    <div class="mt-5 text-center">
                        
                        <div>
                            <p>© <script>document.write(new Date().getFullYear())</script> Soleg. Creado <i class="mdi mdi-heart text-danger"></i> Por <a href="https://www.linkedin.com/in/joel-josue-h-ba5b39215/">Josue Lopez</a></p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}

apps/authentication/templates/login/login.html
{% extends 'auth/base-auth.html' %}
{% load widget_tweaks %}
{% load static %}
{% block title %}SOLEG - Iniciar sesión{% endblock title %}
{% block extra_css %}
    <link href="{% static 'core/libs/sweetalert2/dist/sweetalert2.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock extra_css %}
{% block content %}
<body>
    <div class="account-pages my-5 pt-sm-5">
        <div class="container">

            <div class="row justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-5">
                    <div class="card overflow-hidden">
                        <div class="bg-secondary bg-soft">
                            <div class="d-flex justify-content-center">
                                <div class="col-8 align-self-end pt-3">
                                    <img src="{% static 'img/logo-soleg-negro.png' %}" alt="" class="img-fluid">
                                </div>
                            </div>
                        </div>
                        <div class="card-body pt-3"> 
                            <div class="p-2">
                                <form id="fntLogin" class="needs-validation" novalidate="" action="{% url 'ath:login' %}" method="POST">
                                    {% csrf_token %}
                                    <div class="mb-3 position-relative">
                                        <label for="validationTooltip01" class="form-label">Correo electrónico</label>
                                        {% render_field form.username placeholder="ingrese el correo electrónico"  %}
                                    </div>
                                    <div class="mb-3 position-relative">
                                        <label for="validationTooltip02" class="form-label">Contraseña</label>
                                        <div class="input-group auth-pass-inputgroup">
                                            {% render_field form.password placeholder="ingrese la contraseña" %}
                                            <button class="btn btn-light " type="button" id="password-addon"><i class="mdi mdi-eye-outline"></i></button>
                                        </div>
                                    </div>
                                    <div class="form-check">
                                        {% render_field form.remember_me %}
                                        <label class="form-check-label" for="remember-check">
                                            Recuerdame
                                        </label>
                                    </div>

                                    <div class="mt-3 d-grid">
                                        <button class="g-recaptcha btn btn-primary waves-effect waves-light" 
                                        data-sitekey="6LdAoOEiAAAAAC44TAb-RF_F6125J3WPj20e3tEH" 
                                        data-callback='onSubmit' 
                                        data-action='submit' id="loginEc">Iniciar Sesión <i class="fas fa-sign-in"></i></button>
                                    </div>
                                    <div class="mt-4 text-center">
                                        <a href="" class="text-muted"><i class="mdi mdi-lock me-1"></i> Olvidaste tu contraseña?</a>
                                    </div>
                                </form>
                            </div>
        
                        </div>
                    </div>
                    <div class="mt-5 text-center">
                        
                        <div>
                            <p>© <script>document.write(new Date().getFullYear())</script> Soleg. Creado <i class="mdi mdi-heart text-danger"></i> Por <a href="https://www.linkedin.com/in/joel-josue-h-ba5b39215/">{{creador}}</a></p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block extra_javascript %}
    <script src="{% static 'core/libs/sweetalert2/dist/sweetalert2.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/main-validate.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@emretulek/jbvalidator"></script>
    <script src="https://www.google.com/recaptcha/api.js?render=6LdAoOEiAAAAAC44TAb-RF_F6125J3WPj20e3tEH"></script>
    <script>
        $('#loginEc').click(function(){
            grecaptcha.ready(function() {
                grecaptcha.execute('6LdAoOEiAAAAAC44TAb-RF_F6125J3WPj20e3tEH', {action: 'submit'}).then(function(token) {
                    $('#fntLogin').submit();
                });
            });
        })
    </script>
    <script src="{% static 'auth/js/auth-login.js' %}"></script>
{% endblock extra_javascript %}

apps/web/templates/home/index.html
{% extends 'web/base-web.html' %}
{% load static %}
{% block content %}
<section class="hero-1-bg active" style="background-image: url({% static 'web/images/hero-1-bg-img.png' %})" id="home">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5">
                <h3 class="font-weight-semibold line-height-1_4 mb-4">Soleg <b> - Soluciones Logisticas</b>.
                </h3>
                <!-- <h3 class="font-weight-semibold line-height-1_4 mb-4">Build <b>community</b> & <b>conversion</b> with our suite of <b>social tool</b></h3> -->
                <p class="text-muted font-size-15 mb-4">Bienvenido</p>
                <div class="mt-5">
                    <a href="{% url 'ath:login' %}" class="btn btn-primary me-2">Iniciar Sesión</a>
                </div>
            </div>
            <div class="col-lg-6 offset-lg-1">
                <div class="mt-4 mt-lg-0">
                    <img src="{% static 'web/images/logistica-imagen.png' %}" alt="" class="img-fluid d-block mx-auto">
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Why Choose Us Start -->
<section class="section">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-4">
                <div class="mb-4 mb-lg-0">
                    <div class="p-2 bg-soft-primary d-inline-block rounded mb-4">
                        <div class="icon-xxl uim-icon-primary"><i class="uim uim-cube"></i></div>
                    </div>
                    <h3 class="">Why Choose Us ?</h3>
                    <p class="text-muted mb-4">Nam libero tempore cum soluta as nobis est eligendi optio cumque nihile impedite quo minus id quod maxime.</p>
                    <a href="#" class="btn btn-outline-primary">Learn More</a>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="row">
                    <div class="col-md-6">
                        <div class="wc-box rounded text-center wc-box-primary p-4 mt-md-5">
                            <div class="wc-box-icon">
                                <i class="mdi mdi-collage"></i>
                            </div>
                            <h5 class="font-weight-bold mb-2 wc-title mt-4">Esay To Use</h5>
                            <p class="text-muted mb-0 font-size-15 wc-subtitle">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</p>
                        </div>
                        <div class="wc-box rounded text-center wc-box-primary p-4">
                            <div class="wc-box-icon">
                                <i class="mdi mdi-trending-up"></i>
                            </div>
                            <h5 class="font-weight-bold mb-2 wc-title mt-4">Grow Your Revenue</h5>
                            <p class="text-muted mb-0 font-size-15 wc-subtitle">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="wc-box rounded text-center wc-box-primary p-4">
                            <div class="wc-box-icon">
                                <i class="mdi mdi-security"></i>
                            </div>
                            <h5 class="font-weight-bold mb-2 wc-title mt-4">Analytics Security</h5>
                            <p class="text-muted mb-0 font-size-15 wc-subtitle">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</p>
                        </div>
                        <div class="wc-box rounded text-center wc-box-primary p-4">
                            <div class="wc-box-icon">
                                <i class="mdi mdi-database-lock"></i>
                            </div>
                            <h5 class="font-weight-bold mb-2 wc-title mt-4">Data Privacy</h5>
                            <p class="text-muted mb-0 font-size-15 wc-subtitle">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</p>
                        </div>
                        <div class="wc-box rounded text-center wc-box-primary p-4">
                            <div class="wc-box-icon">
                                <i class="mdi mdi-database-lock"></i>
                            </div>
                            <h5 class="font-weight-bold mb-2 wc-title mt-4">Data Privacy</h5>
                            <p class="text-muted mb-0 font-size-15 wc-subtitle">Sed ut perspiciatis unde omnis iste natus error sit voluptatem.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Why Choose Us End -->

{% endblock content %}

templates/login/base-login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta content="soleg - inicio de sesión" name="description" />
        <meta content="Josue Lopez" name="author" />
        <link rel="shortcut icon" href="{% static 'img/soleg-icon-web.png' %}">
        {% block extra_css %}
        {% endblock extra_css %}
        <link href="{% static 'core/css/bootstrap.min.css' %}" id="bootstrap-style" rel="stylesheet" type="text/css" />
        <link href="{% static 'core/css/icons.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'core/css/app.min.css' %}" id="app-style" rel="stylesheet" type="text/css" />
    </head>
    {% block content %}
    
    {% endblock content %}
        <!-- JAVASCRIPT -->
    <script src="{% static 'core/libs/jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'core/libs/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'core/libs/metismenu/dist/metisMenu.min.js' %}"></script>
    <script src="{% static 'core/libs/simplebar/dist/simplebar.min.js' %}"></script>
    <script src="{% static 'core/libs/node-waves/dist/waves.min.js' %}"></script>
    <script src="{% static 'core/js/app.js' %}"></script>
    {% block extra_javascript %}
    {% endblock extra_javascript %}
</body>
</html>
    

templates/web/base-web.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock title %}</title>
    <meta content="Josue Lopez" name="author" />
    <link rel="shortcut icon" href="{% static 'img/soleg-icon-web.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="PSomos un equipo humano de profesionales, dedicados a generar valor agregado en los procesos de nuestros clientes, mediante la reducción de costos operativos y optimización de recursos." />
    <meta name="keywords" content="logistica, guayaquil, pika, soleg" />
    <!-- favicon -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <!-- css -->
    <link href="{% static 'web/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'web/css/materialdesignicons.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'web/css/style.min.css' %}" rel="stylesheet" type="text/css" />

</head>

<body>

    {% block content %}
    
    {% endblock content %}

    <!-- Footer Start -->
    <div class="footer-alt py-3">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="text-center">
                        <p class="text-white-50 font-size-15 mb-0">© <script>document.write(new Date().getFullYear())</script> Soleg. Creado <i class="mdi mdi-heart text-danger"></i> Por <a href="https://www.linkedin.com/in/joel-josue-h-ba5b39215/">{{creador}}</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->

    <!-- javascript -->
    <script src="{% static 'web/js/jquery.min.js' %}"></script>
    <script src="{% static 'web/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'web/js/scrollspy.min.js' %}"></script>
    <script src="{% static 'web/js/jquery.easing.min.js' %}"></script>
    <!-- feather icon -->
    <script src="{% static 'web/js/feather.js' %}"></script>
    <!-- unicons icon -->
    <script src="{% static 'web/js/unicons.js' %}"></script>
    <!-- Main Js -->
    <script src="{% static 'web/js/app.js' %}"></script>

</body>
</html>